server:
    port: ${PORT:8081}
eureka:
    client:
      service-url:
          defaultZone: http://localhost:8761/eureka
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/clase7
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
